language: node_js
node_js: node
install: yarn install
script: yarn build
cache: yarn
deploy:
  - provider: s3
    access_key_id:
      secure: $AWS_ACCESS_KEY_ID
    secret_access_key:
      secure: $AWS_SECRET_ACCESS_KEY
    bucket: techradar.aoe.com
    skip_cleanup: true
    acl: public_read
    region: eu-central-1
    local_dir: dist
    detect_encoding: true
    on:
      branch: master
  - provider: s3
    access_key_id:
      secure: $AWS_ACCESS_KEY_ID
    secret_access_key:
      secure: $AWS_SECRET_ACCESS_KEY
    bucket: techradar-next.aoe.com
    skip_cleanup: true
    acl: public_read
    region: eu-central-1
    local_dir: dist
    detect_encoding: true
    on:
      branch: v3
